# NumPy

NumPy is a Python package. It stands for 'Numerical Python'. It is a library consisting of multidimensional array objects and a collection of routines for processing of array.

Installing NumPy : Go to Anaconda Prompt & Activate the environment in which you want to install then enter : pip install numpy

## Note :
You don’t need to memorize the name of a module or function. You can always search on the web about a specific module or you can refer to class notebooks. Although, once you start coding on a particular programming language after spending particular time, you will start remembering the names which you often use.

In [2]:
import numpy as np

In [3]:
np.__version__

'1.21.5'

## Numpy Usecase


In [4]:
a=[1,2,3,4,6,7,"abs"]

In [5]:
a

[1, 2, 3, 4, 6, 7, 'abs']

In [6]:
type(a)

list

In [7]:
na=np.array(a)      #numpy uses only one datatype...here it hasconverted everything into string..'1','2','abs'..

In [8]:
na                   #here it has converted everything into string..'1','2','abs'..

array(['1', '2', '3', '4', '6', '7', 'abs'], dtype='<U11')

In [9]:
type(na)

numpy.ndarray

In [10]:
#or
na.dtype

dtype('<U11')

In [11]:
#lets try only with numbers now...

In [12]:
b=[1, 2, 3, 4, 6, 7]

In [13]:
nb=np.array(b)

In [14]:
nb.dtype

dtype('int32')

In [15]:
nb                 ##here it has converted everything into int...1,2,3,...

array([1, 2, 3, 4, 6, 7])

In [16]:
#lets try nested list now...

In [17]:
c=[[1,2,3],[4,5,6]]

In [18]:
type(c)

list

In [19]:
nc=np.array(c)

In [20]:
nc

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
nc[0]

array([1, 2, 3])

In [22]:
#try to find 4

In [23]:
nc[1][0]

4

In [24]:
#try to find 6

In [25]:
nc[1][2]

6

In [26]:
#try to find 3

In [27]:
nc[0][2]

3

In [28]:
y=np.array([1,2,3,4,5])

In [29]:
z=y

In [30]:
z

array([1, 2, 3, 4, 5])

In [31]:
print(y is z)

True


In [32]:
z[4]

5

In [33]:
y[4]

5

In [34]:
#modifying the array now
z[4]=10

In [35]:
y[4]                     #shallow copy

10

In [36]:
z                         ##shallow copy

array([ 1,  2,  3,  4, 10])

In [37]:
y

array([ 1,  2,  3,  4, 10])

In [38]:
print(z is y)           #shallow copy     #here z and y are same objects as we equaled them in cell 45
                                           #only if same objects..true or else false

True


In [39]:
#lets try deep copy now

In [40]:
p=np.array([23,44,55,66,77,88])

In [41]:
p

array([23, 44, 55, 66, 77, 88])

In [42]:
q=np.copy(p)                ##Deep copy

In [43]:
p

array([23, 44, 55, 66, 77, 88])

In [44]:
print(p is q)               #deep copy   #here p and q are not the same objects

False


In [45]:
p

array([23, 44, 55, 66, 77, 88])

In [46]:
p[2]=50

In [47]:
p

array([23, 44, 50, 66, 77, 88])

In [48]:
q                                 #here 2 index of q did not change like the way it changed in p

array([23, 44, 55, 66, 77, 88])

In [49]:
p==q                               #now after making q equal to p, that is the result below

array([ True,  True, False,  True,  True,  True])

In [50]:
for i in range(1,24,2):
    print(i)

1
3
5
7
9
11
13
15
17
19
21
23


In [51]:
for i in range(0.5,24,0.5):
    print(i)                            #limitation of python range.. it can't print floats in range

TypeError: 'float' object cannot be interpreted as an integer

In [52]:
## So, we use numpy a-range/arange to print floats also...like below

for i in np.arange(0.5,24,0.5):
    print(i)                             # A-range/arange means Array Range... in numpy can take floats also
                                            #arange is more advance than numpy arange

0.5
1.0
1.5
2.0
2.5
3.0
3.5
4.0
4.5
5.0
5.5
6.0
6.5
7.0
7.5
8.0
8.5
9.0
9.5
10.0
10.5
11.0
11.5
12.0
12.5
13.0
13.5
14.0
14.5
15.0
15.5
16.0
16.5
17.0
17.5
18.0
18.5
19.0
19.5
20.0
20.5
21.0
21.5
22.0
22.5
23.0
23.5


In [53]:
## Just for practice....

xyz = np.arange(0.5,10.5,0.5)

In [54]:
xyz

array([ 0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,
        6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [55]:
np.arange(0.5:25)

SyntaxError: invalid syntax (1501147230.py, line 1)

In [56]:
np.arange(0.5,25)

array([ 0.5,  1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5,
       11.5, 12.5, 13.5, 14.5, 15.5, 16.5, 17.5, 18.5, 19.5, 20.5, 21.5,
       22.5, 23.5, 24.5])

In [57]:
np.arange(2.5,15.5)

array([ 2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5, 11.5, 12.5,
       13.5, 14.5])

In [58]:
for m in range(1,10):
    print(m)


1
2
3
4
5
6
7
8
9


In [59]:
h=range(6,24):
    print(h)      ...# just practicing to see where I am committing silly mistakes...here the total syntax is wrong for range

SyntaxError: invalid syntax (2646861720.py, line 1)

In [60]:
h

NameError: name 'h' is not defined

# String to numpy array

In [61]:
a=("surya","teja","kolusu")

In [62]:
a


('surya', 'teja', 'kolusu')

In [63]:
a=np.array(a)

In [64]:
a

array(['surya', 'teja', 'kolusu'], dtype='<U6')

In [65]:
"1B2C3C"

'1B2C3C'

In [66]:
#separate the alphabets btwn the string above...like this...

np.fromstring("1C2C3C",sep="C")      .....# from the string above, u are 'sep'arating C and making array 1,2,3
                                          

SyntaxError: invalid syntax (1201337358.py, line 3)

In [67]:
np.fromstring("1$2$3$4$5$", sep="$").sum()

15.0

In [68]:
np.zeros((10,2))     ##'zeros'  #zero array of size 10 * 2...10 rows and 2 columns

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [69]:
np.zeros((5,7))      # default numpy takes float values all the time

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [70]:
np.zeros((5,7),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [71]:
#or
np.zeros((5,7),type(int))

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]], dtype=object)

In [72]:
np.zeros((5,7))+100

array([[100., 100., 100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100., 100., 100.]])

In [73]:
##Python LIST

a=[1,2,3,4]
b=[6,7,8,9]

In [74]:
print(a+b)     #extending the list, not performing the maths operation

[1, 2, 3, 4, 6, 7, 8, 9]


In [75]:
## Numpy Array 

c=np.array([1,2,3,4])
d=np.array([6,7,8,9])

In [76]:
print(c+d)
print(c-d)
                          #See the difference btwn numpy array  & python list

[ 7  9 11 13]
[-5 -5 -5 -5]


In [77]:
#Numpy arrray performs more maths operations over list

In [78]:
x=np.array([1,2,3,4])
y=np.array([6,7,8])

In [79]:
x+y      #x+y gives error...#arrays should be of same zize

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [80]:
np.eye(3,3)   #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
#nested arrays..
u=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [82]:
u

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [83]:
u[0:1]

array([[1, 2, 3, 4]])

In [84]:
u[0:2,1:2]

array([[2],
       [6]])

In [85]:
#print 7,8,11,12 from above      ##..write the row no. 1st and coloumn no. next
u[1:3,2:4]

array([[ 7,  8],
       [11, 12]])

In [86]:
#print 3,4,7,8 from above
u[0:2,2:4]

array([[3, 4],
       [7, 8]])

In [87]:
#print 5,6,9,19 from above
u[1:3,0:2]

array([[ 5,  6],
       [ 9, 10]])

In [88]:
u[1:4]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [89]:
u

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [90]:
u**2   #square

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]], dtype=int32)

In [91]:
u**3   #cube

array([[   1,    8,   27,   64],
       [ 125,  216,  343,  512],
       [ 729, 1000, 1331, 1728]], dtype=int32)

In [92]:
u**4

array([[    1,    16,    81,   256],
       [  625,  1296,  2401,  4096],
       [ 6561, 10000, 14641, 20736]], dtype=int32)

In [93]:
u.shape    #shape of u is 3 rows and 4 coloumns as above

(3, 4)

In [94]:
z=np.array([1,2,3])

In [95]:
z.shape #shape of z is 3 only

(3,)

In [96]:
# Dimension of array... should type " .ndim "

u


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [97]:
u.ndim                                       ##2D array

2

In [98]:
qw=np.array([12,13,14])

In [99]:
qw


array([12, 13, 14])

In [100]:
qw.ndim    #1D array

1

In [101]:
#Size of array

qw.size

3

In [102]:
u.size

12

In [103]:
#datatype of aary

u.dtype

dtype('int32')

In [104]:
qw.dtype

dtype('int32')

In [105]:
## RESHAPE the array

In [106]:
a=np.arange(1,17)

In [107]:
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [108]:
a.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [109]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [110]:
#so..we'll do this..
newa=a.reshape(4,4)

In [111]:
newa    #2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [112]:
newa.ndim

2

In [113]:
newa.shape

(4, 4)

In [114]:
newa.size

16

In [115]:
newa=a.reshape(4,3)

ValueError: cannot reshape array of size 16 into shape (4,3)

In [116]:
newa.reshape(3,5,2)

ValueError: cannot reshape array of size 16 into shape (3,5,2)

In [117]:
newb=newa.reshape(2,2,4)        ##3D array

In [118]:
newb

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [119]:
#try to find 9 from above...
                                       #imagine a 3d figure 
newb[1,0,0]

9

In [120]:
#try finding 6..
newb[0,1,1]

6

In [121]:
newa

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [122]:
np.diag(newa)            ## Printing Diagnol

array([ 1,  6, 11, 16])

In [123]:
##Random number generation form..

#i did not understand this.. should watch the recording 2nd time.. 

In [124]:
##Random Number Generation


In [125]:
np.random.rand(2,3)    #random array sixe of 2*3 will be created

array([[0.19883697, 0.69314255, 0.18162075],
       [0.51591026, 0.80636942, 0.69233503]])

In [126]:
np.random.randint(1,10,6)   #give me 6 random integers btwn 1 and 10

array([1, 7, 2, 2, 9, 5])

In [127]:
#Random Seed.... It is just a value that we give randomly

In [128]:
np.random.seed(1334)      
np.random.randint(1,10,5)
#surya and gurpreet                 #Surya & GP will get the same array data as random seed is same

array([4, 7, 9, 3, 1])

In [129]:
np.random.seed(123)      
np.random.randint(1,20,4)
# Augustine and Richard             #Augustine and richard will get the same array data as random seed is same

array([14,  3,  3,  7])

In [143]:
np.random.seed(123)      
np.random.randint(1,10,7)

array([3, 3, 7, 2, 4, 7, 2])

In [169]:
np.random.seed(12345)  
a=np.random.randint(1,24,6).reshape(3,2)
b=np.random.randint(1,30,6).reshape(3,2)

In [170]:
a

array([[ 3,  6],
       [ 2,  5],
       [10,  6]])

In [171]:
b

array([[ 3,  2],
       [23, 18],
       [28, 15]])

In [ ]:
##Maths Operations

In [164]:
np.sqrt(a)  #square root

array([[1.73205081, 2.44948974],
       [1.41421356, 2.23606798],
       [3.16227766, 2.44948974]])

In [187]:
np.add(a,b)

array([[ 6,  8],
       [25, 23],
       [38, 21]])

In [175]:
np.multiply(a,b)

array([[  9,  12],
       [ 46,  90],
       [280,  90]])

In [176]:
np.divide(a,b)

array([[1.        , 3.        ],
       [0.08695652, 0.27777778],
       [0.35714286, 0.4       ]])

In [178]:
np.mean(a)

5.333333333333333

In [179]:
np.mean(b)

14.833333333333334

In [181]:
np.median(a)

5.5

In [182]:
np.std(b)   #standard deviation

9.616247824501105

In [184]:
np.var(b)  #variance

92.47222222222224

In [194]:
np.log10(a) #log10

array([[0.47712125, 0.77815125],
       [0.30103   , 0.69897   ],
       [1.        , 0.77815125]])

In [188]:
np.max(a) #max number

10

In [195]:
np.min(b) #min number

2