In [1]:
import numpy as np

In [2]:
a = [[1,2,3],[4,5,6],[7,8,9]]

In [3]:
a= np.array(a)

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# size gives the total number of elements

In [5]:
a.size

9

# ndim gives the dimensison, 2 for a matrix, 1 for a vector

In [6]:
a.ndim

2

# shape gives the number of elements along each dimension 

In [7]:
a.shape

(3, 3)

# dtype gives the data type contained in the array

In [8]:
a.dtype

dtype('int32')

#  Extract a diagonal 

In [9]:
x = np.arange(16).reshape((-1,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
np.diag(x)

array([ 0,  5, 10, 15])

# Reshape

In [11]:
x = np.arange(16).reshape((-1,4)) #make 4 cols 
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
x = np.arange(16).reshape((4,4)) #make 4 rows & 4 cols 
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
x = np.arange(16).reshape((8,-1)) # make 8 rows 
x

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

# Random number generation
Random number generation (from Uniform distribution)

In [31]:
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1

[[0.9639722  0.6047495  0.55998871]
 [0.73969151 0.46030335 0.29839402]]


In [40]:
np.random.randint(1,10,3)#randint (low, high, # of samples to be drawn)

array([3, 7, 7])

In [41]:
np.random.randint(1,100,(3,3)) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)

array([[24, 97,  8],
       [84, 24, 54],
       [92, 36, 77]])

# Maths

In [17]:
mat1 = np.array(np.random.randint(1,10,9)).reshape(3,3) #Creating random Numpy array of size 3x3
mat2 = np.array(np.random.randint(1,10,9)).reshape(3,3)

In [18]:
mat1

array([[4, 5, 8],
       [8, 7, 4],
       [2, 7, 1]])

In [19]:
mat2

array([[3, 5, 9],
       [6, 2, 5],
       [5, 4, 1]])

In [20]:
np.sqrt(mat1)  #Sq-root of 1st matrix

array([[2.        , 2.23606798, 2.82842712],
       [2.82842712, 2.64575131, 2.        ],
       [1.41421356, 2.64575131, 1.        ]])

In [21]:
np.log10(mat1) #log 1o

array([[0.60205999, 0.69897   , 0.90308999],
       [0.90308999, 0.84509804, 0.60205999],
       [0.30103   , 0.84509804, 0.        ]])

In [22]:
np.mean(mat1) 

5.111111111111111

In [23]:
np.median(mat2)

5.0

In [24]:
np.std(mat2)

2.216659704806667

In [25]:
np.var(mat2)

4.913580246913581

In [26]:
np.max(mat2)

9

In [27]:
np.min(mat2)

1